version: '3'
#CMD: docker-compose up -d

services:

  postgres:
    image: postgres:15.3
    domainname: postgres
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calendar
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2


